on:
#  push:
  workflow_dispatch:
    inputs:
      project:
        description: "Repo Name, example madevops-jira-integration"
        required: true
        default: "madevops-jira-integration"
env:
  PROJECT_NAME: atmarampradhan/${{ inputs.project }}
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
