on:
#  push:
  workflow_dispatch:
    inputs:
      project:
        description: "Repo Name, example madevops-jira-integration"
        required: true
        default: "madevops-jira-integration"
env:
  PROJECT_NAME: atmarampradhan/${{ inputs.project }}
jobs:
  set:
    runs-on: [ master ]
    environment: test
    steps:
      - uses: atmarampradhan/github-actions-course-template@v1
        with:
          location: ${{ env.PROJECT_NAME }}
